[package]
name = "twoyi"
version = "0.6.0"
edition = "2021"

[lib]
name = "twoyi"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
log = "0.4"
android_logger = "0.13"
libc = "0.2"
once_cell = "1.18"
unix_socket = "0.5.0"
# Ensure these match your NDK version
ndk = { version = "0.8", features = ["event", "native_window"] }
ndk-sys = "0.5"
