[package]
name = "twoyi"
version = "0.6.0"
edition = "2021"

[lib]
name = "twoyi"
crate-type = ["cdylib"]

[dependencies]
# Use 0.21+ for better Android 12-14 support
jni = "0.21.1" 
log = "0.4"
android_logger = "0.13"

# If you use the ndk-glue or ndk-context crates, make sure they are updated
ndk = "0.8.0"
